name: my_env
channels:
  - defaults
dependencies:
  - python=3.9.0
  - pip=21.0.1
  - pip:
    - matplotlib==3.5.3
    - pandas==1.5.0
    - seaborn==0.12.1
    - session_info==1.0.0
    - matplotlib==3.1.3
    - seaborn==0.10.0
    - sklearn==1.1.2
    - IPython==8.5.0
    - jupyter_client==7.3.5
    - jupyter_core==4.11.1
    - jupyterlab==3.4.7
    - notebook==6.4.12
